version: "3.8"

services:
  training-api:
    build:
      context./training-api
    ports:
      - "5002:5000"
    networks:
      - network-b
    environment:
      - MODEL_REPO=/usr/src/myapp/models2
    volumes:
      - "/home/rijkersniek/models:/src/usr/models2"
  prediction-api:
    build:
      context: prediction-api
    container_name: prediction_api
    depends_on: training_api
    ports:
      - "5001:5000"
    networks:
      - network-a
      - network-b
    environment:
      - MODEL_REPO=/usr/src/myapp/models2
    volumes:
      - "/home/rijkersniek/models:/src/usr/models2"
  prediction-ui:
    build:
      context: prediction-ui
      ports:
        - "5000:5000"
      networks:
        - network-a
      environment:
        - PREDICTOR_API=http://predictor-api-server:5000/diabetes_predictor
networks:
  network-a
  network-b



    